# ============================================================
# Stage 1: Install PHP dependencies with Composer
# ============================================================
FROM php:8.4-cli-alpine AS composer_build

COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install --no-dev --optimize-autoloader --no-scripts

COPY . .

RUN composer run-script post-autoload-dump

# ============================================================
# Stage 2: Build frontend assets with Node/Vite
# ============================================================
FROM node:20-alpine AS node_build

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci

COPY resources/ resources/
COPY vite.config.* ./

RUN npm run build

# ============================================================
# Stage 3: Production image
# ============================================================
FROM php:8.4-fpm-alpine AS production

# Install only the PHP extensions this project actually uses:
#  - pdo_sqlite: DB_CONNECTION=sqlite in .env
#  - mbstring:  required by Laravel
#  - opcache:   production performance
#  - pcntl:     Laravel queue/scheduling support
#  - ctype:     character type checking (not bundled in Alpine)
#  - fileinfo:  MIME type detection (not bundled in Alpine)
#  - session:   session handling (not bundled in Alpine)
#  - openssl:   encryption (Laravel APP_KEY)
RUN apk add --no-cache \
    php83-pdo_sqlite \
    php83-mbstring \
    php83-opcache \
    php83-pcntl \
    php83-ctype \
    php83-fileinfo \
    php83-session \
    php83-openssl

# OPcache production configuration
RUN echo "opcache.enable=1"           >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.memory_consumption=256" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.interned_strings_buffer=16" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.max_accelerated_files=10000" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.validate_timestamps=0" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.save_comments=1"  >> /usr/local/etc/php/conf.d/opcache.ini

# Create non-root user
RUN addgroup -g 1000 laravel && adduser -u 1000 -G laravel -s /bin/sh -D laravel

WORKDIR /var/www/html

# Copy application source (chown so laravel user owns it)
COPY --chown=laravel:laravel . .

# Copy Composer dependencies from build stage (no dev deps)
COPY --chown=laravel:laravel --from=composer_build /app/vendor vendor/

# Copy bootstrap cache (generated by post-autoload-dump)
COPY --chown=laravel:laravel --from=composer_build /app/bootstrap ./bootstrap

# Copy compiled frontend assets
COPY --from=node_build /app/public/build public/build

# Ensure storage and bootstrap/cache are writable
RUN mkdir -p storage/framework/{cache,sessions,views} \
    && mkdir -p bootstrap/cache \
    && chown -R laravel:laravel storage bootstrap/cache

USER laravel

EXPOSE 9000

CMD ["php-fpm"]
